## This parameter file configures the Experience Triage MEL module
navigator:
  ros__parameters:
    loc:
      experience_triage:
        # the module type (don't change this param)
        type: "experience_triage"