## This parameter file configures the Random Experiences MEL module
navigator:
  ros__parameters:
    loc:
      random_experiences:
        # the module type (don't change this param)
        type: "random_experiences"

        verbose: false
        in_the_loop: true
        num_desired_experiences: 10