/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: false
    log_enabled:
      [
        "navigator",
        "map_projector",
        "tactic",
        "tactic.module",
        "mission_planning_server",
        "state_machine",
        "pose_graph",
        "stereo.pipeline",
        "path_tracker",
      ]

    # The sensor frame from the urdf (also defines the rig name)
    camera_frame: front_xb3
    # The control frame from the urdf
    robot_frame: base_link
    #
    lidar_topic: not_used

    ############ map projection configuration ############
    map_projection:
      origin_lat: 43.78220
      origin_lng: -79.4661
      origin_theta: 1.3 # positive == clockwise
      scale: 1.0

    ############ tactic configuration ############
    tactic:
      extrapolate_odometry: true # path tracker
      localization_only_keyframe: true
      localization_skippable: false
      default_loc_cov: [1.0, 0.5, 0.5, 0.25, 0.25, 0.5]
      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 20
        search_back_depth: 10
        distance_warning: 3.0
      live_mem:
        enable: true
        lookahead_distance: 100
        window_size: 10
      map_mem:
        enable: true
        lookahead_distance: 15
        vertex_life_span: 10

      visualize: true
      vis_loc_path_offset: [0., 0., 0.]

    ############ pipeline configuration ############
    pipeline:
      type: stereo
      preprocessing: ["extraction", "triangulation"]
      odometry: ["recall", "matcher", "ransac", "steam", "vertex_test"]
      bundle_adjustment: ["recall", "steam"]
      localization:
        [
          "recall",
          "sub_map_extraction",
          "tod_recognition",
          "experience_triage",
          "migration",
          "matcher",
          "ransac",
          "steam",
        ]

    preprocessing:
      # conversion+extraction module
      extraction:
        type: conversion_extraction

        # specify which conversions to do between different image formats from:
        # RGB_TO_GRAYSCALE, RGB_TO_COLOR_CONSTANT
        conversions: ["RGB_TO_GRAYSCALE", "RGB_TO_COLOR_CONSTANT"]
        color_constant:
          weights: [0.43]
          visualize_raw_features: false

        extractor:
          type: ASRL_GPU_SURF

          channels: ["grayscale", "cc_0.430000"]

          surf:
            threshold: 0.000001
            upright_flag: true
            nOctaves: 4
            nIntervals: 4
            initialScale: 1.5
            edgeScale: 1.5
            l1: 2.0 # 3.f/1.5f
            l2: 3.333333 # 5.f/1.5f
            l3: 2.0 # 3.f/1.5f
            l4: 0.666667 # 1.f/1.5f
            initialStep: 1
            targetFeatures: 1000
            detector_threads_x: 16
            detector_threads_y: 16
            regions_horizontal: 16
            regions_vertical: 16
            regions_target: 1000
            stereoDisparityMinimum: 0.0
            stereoDisparityMaximum: 64.0
            stereoCorrelationThreshold: 0.79
            stereoYTolerance: 0.9
            stereoScaleTolerance: 0.9

      triangulation:
        visualize_features: false
        visualize_stereo_features: false

    odometry:
      recall:
        type: landmark_recall

        landmark_source: live

      matcher:
        check_response: true
        matching_pixel_thresh: 400.0
        tight_matching_pixel_thresh: 20.0
        tight_matching_x_sigma: 0.6 # in s
        tight_matching_y_sigma: 0.6 # in s
        tight_matching_theta_sigma: 0.6 # in s
        prediction_method: se3
        max_point_depth: 500.0
        descriptor_thresh: 0.1
        parallel_threads: 8
        visualize_feature_matches: false

      ransac:
        iterations: 2000
        threshold: 5.0
        early_stop_min_inliers: 200
        visualize_ransac_inliers: true
        min_inliers: 15

      steam:
        verbose: false
        iterations: 5

        perform_planarity_check: false
        plane_distance: 20.0
        min_point_depth: 0.0
        max_point_depth: 200.0
        use_T_q_m_prior: false
        # Smoothing based on vehicle dynamics,
        # tune these for your robot in your robot-specific config
        # E.g. a nonholonomic ground vehicle on rugged terrain:
        trajectory_smoothing: true
        ## smoothing factor
        ## zero mean white noise on acceleration
        ## one-sigma standard deviation for linear acceleration (m/s/s)
        lin_acc_std_dev_x: 10.0 ## lifted from max acceleration in grizzly launch
        lin_acc_std_dev_y: 10.0 ## grizzly does not strafe very fast
        lin_acc_std_dev_z: 10.0 ## neither does it jump quickly, except for going over bumps
        ## one-sigma standard devitation for angular acceleration (rad/s/s0)
        ang_acc_std_dev_x: 1.0 # roll rate, should be low
        ang_acc_std_dev_y: 1.0 # pitch rate,
        ang_acc_std_dev_z: 1.0 # yaw rate, approx 2 deg

        velocity_prior: false
        lin_vel_mean_x: 4.0
        lin_vel_mean_y: 0.0
        lin_vel_mean_z: 0.0
        ang_vel_mean_x: 0.0
        ang_vel_mean_y: 0.0
        ang_vel_mean_z: 0.0

        lin_vel_std_dev_x: 8.0 ## the grizzly is usually within +- 3.0 m/s
        lin_vel_std_dev_y: 3.0
        lin_vel_std_dev_z: 0.5
        ang_vel_std_dev_x: 0.5
        ang_vel_std_dev_y: 0.5
        ang_vel_std_dev_z: 0.2

        depth_prior_enable: false
        pose_prior_enable: false

      vertex_test:
        match_threshold_min_count: 100
        match_threshold_fail_count: 15

    localization:
      recall:
        type: landmark_recall
        landmark_source: live

      migration:
        type: landmark_migration

      matcher:
        target_match_count: 200
        min_match_count: 20
        min_track_length: 1
        max_landmark_depth: 200.0
        matching_pixel_thresh: 200
        tight_matching_pixel_thresh: 50
        min_response_ratio: 0.2
        time_allowance: 2000.0
        descriptor_thresh_cpu: 0.115
        screen_matched_landmarks: true
        max_depth_diff: 5.0
        visualize: true

      steam:
        verbose: false
        iterations: 15
        use_T_q_m_prior: true

        save_trajectory: false
        trajectory_smoothing: false
        velocity_prior: false
        depth_prior_enable: false
        pose_prior_enable: true

    bundle_adjustment:
      recall:
        type: stereo_windowed_recall
        window_size: 5

      steam:
        verbose: false

        perform_planarity_check: false
        plane_distance: 20.0
        min_point_depth: 1.0
        max_point_depth: 800.0
        use_T_q_m_prior: false
        trajectory_smoothing: true
        velocity_prior: false
        depth_prior_enable: true
        depth_prior_weight: 1000000000.0
