# Gains for MPC
/**:
  ros__parameters:
    path_tracker:
      # Controller gains
      TargetLinearSpeed: [0.2, 0.5, 0.8, 1.2, 2.5]
      HeadingErrorGain: [0.75, 0.75, 0.75, 0.75, 0.75]
      LateralErrorGain: [0.3, 0.3, 0.3, 0.3, 0.3]
      SaturationLimit: [2.0, 2.0, 2.0, 2.0, 2.0]
      LookAheadDistance: [0.5, 0.75, 1.2, 1.5, 3.0]
      AngularLookAhead: [0.3, 0.3, 0.3, 0.3, 0.3]

      # if curv[vertex_number] > thresh[i], take speed [i]
      CurvatureThresholds: [0.01, 0.2, 1.5, 3.0, 5.0]
