/**:
  ros__parameters:
    ############ system configuration ############

    ############ map projection configuration ############
    map_projection:
      origin_lat: 43.78215
      origin_lng: -79.46605
      origin_theta: -0.2 # positive == clockwise
      scale: 1.0

    ############ tactic configuration ############
    tactic:
      visualize: true

    ############ pipeline configuration ############
    pipeline:
      # pipeline parameters
      map_voxel_size: 0.3

    preprocessing:
      preprocessing:
        num_channels: 128
        vertical_angle_res: 0.0054971
        polar_r_scale: 2.0
        r_scale: 4.0
        h_scale: 1.0
        frame_voxel_size: 0.3
        visualize: true

    odometry:
      recall:
        type: "lidar.map_recall"
        map_voxel_size: 0.3
        visualize: true
      keyframe_test:
        type: "lidar.keyframe_test"
        min_translation: 5.0
        min_rotation: 30.0
        min_matched_points_ratio: 0.5

    localization:
      recall:
        type: "lidar.windowed_map_recall"
        map_voxel_size: 0.3
        depth: 1
        visualize: true
