## this parameter file is used to configure the image conversion module
navigator:
  ros__parameters:
    converter:
      conversion:
        # the module type (don't change this param)
        type: "image_conversion"

        # specify which conversions to do between different image formats from:
        # RGB_TO_GRAYSCALE, RGB_TO_COLOR_CONSTANT
        conversions: ["RGB_TO_GRAYSCALE"]

        # color constant settings
        color_constant:
          weights: [0.43]
          histogram_equalization: false
