/**:
  ros__parameters:
    tactic:
      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 20
        search_back_depth: 10
        distance_warning: 3.0
    preprocessing:
      type: "pcl_preprocessing"
      lidar_n_lines: 64
      polar_r_scale: 4.0
      r_scale: 4.0
      h_scale: 0.5
      frame_voxel_size: 0.1
      visualize: true
    odometry_recall:
      type: "lidar_recall"
      map_voxel_size: 0.2
      visualize: true
    odometry_icp:
      type: "icp"
      source: "live"
      n_samples": 1000
      max_pairing_dist": 2.0
      max_planar_dist": 0.3
      avg_steps": 5
      max_iter": 100
    keyframe_test:
      type: "keyframe_test"
      min_translation: 3.0
      min_rotation: 30.0
    map:
      type: "map_maintenance"
      map_voxel_size: 0.2
      visualize: true
    localization_recall:
      type: "lidar_windowed_recall"
      map_voxel_size: 0.2
      depth: 1
      visualize: true
    localization_icp:
      type: "icp"
      source: "map"
      n_samples": 1000
      max_pairing_dist": 2.0
      max_planar_dist": 0.3
      avg_steps": 5
      max_iter": 100
