/**:
  ros__parameters:
    preprocessing:
      type: "pcl_preprocessing"
      lidar_n_lines: 64
      r_scale: 4.0
      h_scale: 0.5
      frame_voxel_size: 0.1
      visualize: true
    recall:
      type: "recall"
      map_voxel_size: 0.03
      visualize: true
    icp:
      type: "icp"
      n_samples": 1000
      max_pairing_dist": 2.0
      max_planar_dist": 0.3
      avg_steps": 5
      max_iter": 100
    keyframe_test:
      type: "keyframe_test"
    map:
      type: "map_maintenance"
      map_voxel_size: 0.03
      visualize: true
